---

- name:
  user: 
    name: openhab
    groups: 
        - dialout
        - tty
#        - bluetooth
        - audio
    append: yes

- name: "configure systemd"
  systemd:
    name: openhab2
    daemon_reload: yes
    enabled: true
    state: started 

- name: cron job
  cron:
    name: "restart openhab"
    minute: "10"
    hour: "5"
    weekday: "0"
    job: 'systemctl restart nginx.service'
    cron_file: openhab2
    user: root

- name: Checkout openhab config
  git:
    repo: "{{ openhab_conf_repo }}"
    dest: "{{ openhab_conf_repo_dest }}"
    accept_hostkey: yes
  become: yes

# Check if openhab conf dir exists
- name: check if conf dir is directory 
  stat:
    path: "{{ openhab_data }}/conf"
  register: conf_dir_available

# Remove openhab config directories
- name: 
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ openhab_data }}/conf"
    - "{{ openhab_data }}/userdata"
    - "{{ openhab_data }}/addons"
    - "{{ openhab_data }}/.java"
  when: conf_dir_available.stat.isdir is defined and conf_dir_available.stat.isdir
  

- name: Create symbolic link to conf folder 
  file:
    src: "{{ openhab_conf_repo_dest }}/conf"
    dest: "{{ openhab_data }}/conf"
    state: link

- name: Create symbolic link to userdata folder 
  file:
    src: "{{ openhab_conf_repo_dest }}/userdata"
    dest: "{{ openhab_data }}/userdata"
    state: link

- name: Create symbolic link to addons folder 
  file:
    src: "{{ openhab_conf_repo_dest }}/addons"
    dest: "{{ openhab_data }}/addons"
    state: link

- name: Create symbolic link to .java folder 
  file:
    src: "{{ openhab_conf_repo_dest }}/.java"
    dest: "{{ openhab_data }}/.java"
    state: link

- name: Change ownership of openhab config
  file:
    path: "{{ openhab_data }}"
    owner: openhab
    group: openhab
    recurse: yes
  become: yes

#- name: Create expected folders if they don't already exist
#  file:
#    path: "{{ item }}"
#    state: directory
#    owner: openhab
#    group: openhab
#  become: yes
#  become_user: openhab
#  with_items:
#    - "{{ openhab_data }}/conf"
#    - "{{ openhab_data }}/userdata"
#    - "{{ openhab_data }}/addons"
#    - "{{ openhab_data }}/.java"

- name: set EXTRA_JAVA_OPTS
  lineinfile:
    path: "/etc/default/openhab2"
    regexp: '^EXTRA_JAVA_OPTS='
    line: 'EXTRA_JAVA_OPTS="-Dpython.path=/etc/openhab2/automation/lib/python/lib/python2.7/site-packages/ -Dgnu.io.rxtx.SerialPorts=/dev/ttyACM0:/dev/ttyACM1:/dev/ttyUSB0:/dev/ttyUSB1:/dev/ttyS0:/dev/ttyS2:/dev/ttyAMA0"'



