---
- name: update package cache for Debian and Ubuntu
  apt:
     update_cache: "{{apt_config.update_cache}}"
     cache_valid_time: "{{apt_config.cache_valid_time}}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install commonly-named packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - python3
  - python3-pip
  - gcc
  - sysstat
  - python3-passlib
 
- name: install fedora-specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-firewall
    - python3-devel
    - redhat-rpm-config
    - python2
    - python2-dnf
    - libselinux-python
    - firewalld
    - which
  when: ansible_distribution == "Fedora"

- name: install debian-specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-dev
    - python3-passlib
  when: ansible_distribution == "Debian" or ansible_distribution == 'Ubuntu'

- name: install debian-required pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - appdirs
    - packaging
  when: ansible_distribution == "Debian" or ansible_distribution == 'Ubuntu'

- name: create user
  user:
    name: "{{ ha_user }}"
    comment: "Home Assistant"
    createhome: no
    system: yes
    shell: "/sbin/nologin"

- name: create directory
  file:
    path: "{{ ha_conf_dir }}"
    state: directory
    mode: 02775
    owner: "{{ ha_user }}"
    group: "{{ ha_user }}"
